- name: configuration of mysql server using roles
  hosts: mysql
  become: yes
  vars_files:
  - /var/expense/mysql_credentials.yaml # create this file and place required credentials when ansible server is re created
  roles:
    - mysql