- name: install and run nginx server
  ansible.builtin.package:
    name: nginx
    state: present
  
- name: run and enable nginx server
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: creating an app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download the frontend code
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip
  
- name: extract the downloaded code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /app
    remote_src: yes

- name: download the frontend code
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip

- name: extract the frontend code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html

- name: copy expense conf file
  ansible.builtin.template:
    name: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf 

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted